# https://github.com/yeasy/docker-compose-files/tree/master/hyperledger
# This compose file will start a Hyperledger Fabric 1.0 MVE, including
# * 2 ca (not in use now)
# * 1 orderer
# * 4 peers in 2 orgs
# * cli for testing

version: '2.0'

services:
# ca.org1.example.com:
#   extends:
#     file: base-kafka.yaml
#     service: ca.org1.example.com

# ca.org2.example.com:
#   extends:
#     file: base-kafka.yaml
#     service: ca.org2.example.com

  cli:
    extends:
      file: base-kafka.yaml
      service: cli

  orderer.example.com:  # There  can be multiple orderers
    extends:
      file: base-kafka.yaml
      service: orderer.example.com
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3

  peer0.org1.example.com:
    extends:
      file: base-kafka.yaml
      service: peer0.org1.example.com
    depends_on:
      - orderer.example.com

  peer1.org1.example.com:
    extends:
      file: base-kafka.yaml
      service: peer1.org1.example.com

  peer0.org2.example.com:
    extends:
      file: base-kafka.yaml
      service: peer0.org2.example.com

  peer1.org2.example.com:
    extends:
      file: base-kafka.yaml
      service: peer1.org2.example.com

# ZooKeeper services, at least 3 nodes
  zookeeper0:
    extends:
      file: base-kafka.yaml
      service: zookeeper0

  zookeeper1:
    extends:
      file: base-kafka.yaml
      service: zookeeper1

  zookeeper2:
    extends:
      file: base-kafka.yaml
      service: zookeeper2

# Kafka services, at least 4 node to tolerant work with 1 node failure
  kafka0:
    extends:
      file: base-kafka.yaml
      service: kafka0
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka1:
    extends:
      file: base-kafka.yaml
      service: kafka1
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka2:
    extends:
      file: base-kafka.yaml
      service: kafka2
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka3:
    extends:
      file: base-kafka.yaml
      service: kafka3
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

#networks:
#  default:
#    external:
#      name: hyperledger_fabric
